Hospital_management/catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from .import views as views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'main/$',views.main_home,name="main_home"),
    url(r'test/$',views.tests,name="test"),
   
    url(r'home/$',views.home,name="home"),
    url(r'aboutus/$',views.aboutus,name="aboutus"),
    url(r'team/$',views.team,name="team"),
    url(r'service$',views.service,name="service"),
    url(r'contactus/$',views.contactus,name="contact"),
    url(r'team/$',views.team,name="team"),
    url(r'^takeapoint/$',views.takeapoint,name='takeapoint'),
    url(r'^viewapoint/$',views.viewapoint,name='viewapoint'),
    url(r'^viewapoint/(\w+)',views.patientdetail, name='patientdetail'),
    url(r'^cancelapoint/$',views.cancelapoint,name='cancelapoint'),
    url(r'^givemedicine/$',views.givemed,name='givemedicine'),
    url(r'^history/$',views.history,name='history'),
    url(r'^myappoint/$',views.myappoint,name='myappoint'),
    url(r'^history/(?P<date>[A-Za-z]?%20[0-9]{2}?%20[0-9]{4})/$', views.tests, name='index'),

    url(r'^ajax/slots/$', views.load_slots, name='ajax_load_slots'),
    url(r'^ajax/finalslots/$', views.load_finalslots, name='ajax_load_finalslots'),
    url(r'login/$', auth_views.login, {'template_name': 'login.html'},name='login'),
    url(r'register/$',views.register, name='register'),
    # xurl(r'register2/$',views.register2,name='register2'),
    url(r'logout/$',auth_views.logout,{'next_page': '/main'},name='logout'),
    #url(r'logout/$',auth_views.LogoutView.as_view(template_name='logout.html')),
    url(r'password_change/$',auth_views.PasswordChangeView.as_view(template_name='registration\password_change.html',success_url='/password_change_done')),
    url(r'password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration\password_change_done.html')),
    url(r'password_reset/$',auth_views.PasswordResetView.as_view(template_name='registration\password_reset_form.html',email_template_name='password_reset_email.html',subject_template_name='registration\password_reset_subject.txt',success_url='/password_reset_done/',from_email='support@yoursite.ma')),
    url(r'password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='registration\password_reset_done.html')),
    url(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='registration\password_reset_confirm.html',success_url='/password_reset_complete/')),
    url(r'password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration\password_reset_complete.html'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hospital_management/localib/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('catalog.urls')),
]

Hospital_management/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid 
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Patient(models.Model):
    u_id=models.OneToOneField(User,on_delete=models.CASCADE)
    First_Name=models.CharField(max_length=40)
    Last_Name=models.CharField(max_length=40)
    Middle_Name=models.CharField(max_length=40)
    Address=models.CharField(max_length=200)
    Date_Of_Birth=models.DateField()
    Blood_Grp=models.CharField(max_length=8)
    Profile_pic= models.FileField(upload_to="profilepics/")

    def __str__(self):
        full_name=self.First_Name+self.Middle_Name+self.Last_Name
        # return self.First_Name
        return '{0} {1} {2} {3} {4} {5} {6}'.format(self.u_id,self.First_Name,self.Last_Name,self.Middle_Name,self.Address,self.Date_Of_Birth,self.Profile_pic)

    # def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        # return reverse('patient-detail', args=[str(self.id)])


class Doctor(models.Model):
    u_id=models.OneToOneField(User,on_delete=models.CASCADE)
    First_Name=models.CharField(max_length=40)
    Last_Name=models.CharField(max_length=40)
    Middle_Name=models.CharField(max_length=40)
    Address=models.CharField(max_length=200)
    Date_Of_Birth=models.DateField()
    Blood_Grp=models.CharField(max_length=8)
    Degree=models.CharField(max_length=100)
    Description=models.CharField(max_length=200)
    Profile_pic= models.FileField(upload_to="profilepics/")

    def __str__(self):
        full_name=self.First_Name+self.Middle_Name+self.Last_Name
        return self.First_Name

class Staff(models.Model):
    u_id=models.OneToOneField(User,on_delete=models.CASCADE)
    First_Name=models.CharField(max_length=40)
    Last_Name=models.CharField(max_length=40)
    Middle_Name=models.CharField(max_length=40)
    Address=models.CharField(max_length=200)
    Date_Of_Birth=models.DateField()
    Blood_Grp=models.CharField(max_length=8)
    Date_of_joining=models.DateField()
    Profile_pic= models.FileField(upload_to="profilepics/")

    def __str__(self):
        full_name=self.First_Name+self.Middle_Name+self.Last_Name
        # return self.First_Name
        return '{0} {1} {2} {3} {4} {5} {6}'.format(self.u_id,self.First_Name,self.Last_Name,self.Middle_Name,self.Address,self.Date_Of_Birth,self.Profile_pic)



class Timings(models.Model):
    Doctor_id=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    Contact_Time = models.TimeField()
    def __str__(self):
        return str(self.Contact_Time)


class Slots(models.Model):
    Doctor_id=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    Slot_Time = models.CharField(max_length=15)
    def __str__(self):
        return str(self.Slot_Time)


class Appointment(models.Model):
    u_id=models.ForeignKey(User,on_delete=models.CASCADE)
    Doctor_id=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    Slot_Time=models.ForeignKey(Slots,on_delete=models.CASCADE)
    Date=models.DateField()
    Taken_time=models.TimeField()
    def __str__(self):
        tp=str(self.Date)
        ta=str(self.Slot_Time)
        return '{0} {1}'.format(tp,ta)
        return (tp,ta)


class CancelAppointments(models.Model):
    u_id=models.ForeignKey(User,on_delete=models.CASCADE)
    Doctor_id=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    #Slot_Time=models.ForeignKey(Slots,on_delete=models.CASCADE)
    Date=models.DateField()
    # Taken_time=models.TimeField()
    def __str__(self):
        return '{0} {1} {2}'.format(self.u_id,self.Doctor_id,self.Date)

class medicine(models.Model):
    medicine_name=models.CharField(max_length=250)
    description=models.CharField(max_length=250)
    def __str__(self):
        return '{0}'.format(self.medicine_name)


class historydata(models.Model):
    u_id=models.CharField(max_length=100)
    Doctor_id=models.CharField(max_length=100,default="")
    date=models.DateField()
    Med_1=models.CharField(max_length=120)
    m1_days=models.CharField(max_length=100)
    m1_times_a_day=models.CharField(max_length=100)
    '''Med_2=models.ForeignKey(medicine,on_delete=models.CASCADE,related_name='m2')
    m2_days=models.CharField(max_length=100)
    m2_times_a_day=models.CharField(max_length=100)
    Med_3=models.ForeignKey(medicine,on_delete=models.CASCADE,related_name='m3')
    m3_days=models.CharField(max_length=100)
    m3_times_a_day=models.CharField(max_length=100)
    Med_4=models.ForeignKey(medicine,on_delete=models.CASCADE,related_name='m4')
    m4_days=models.CharField(max_length=100)
    m4_times_a_day=models.CharField(max_length=100)
    Med_5=models.ForeignKey(medicine,on_delete=models.CASCADE,related_name='m5')
    m5_days=models.CharField(max_length=100)
    m5_times_a_day=models.CharField(max_length=100)'''
    description=models.CharField(max_length=300)

    def __str__(self):
             return '{0} {1}'.format(self.date,self.Doctor_id)

    
        

# Create your models here.
'''class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    book_pic = models.FileField(upload_to="profilepics/")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.id,self.book.title)


class Author(models.Model):
    """
    Model representing an author.
    """
    id=models.CharField(max_length=12,primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ["last_name","first_name"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        #return '{0}, {1}'.format(self.last_name,self.first_name)
        return '{0} {1} {2}'.format(self.last_name,self.first_name,str(self.id))
        #return (str(self.id))

    def __repr__(self):
    	return (str(self.id))
'''

Hospital_management/catalog/templates/appoint.html
 {% comment %} {% extends "main_base.html" %} {% endcomment %}
 {% load static %}
 <section class="contact" id="takeapoint">
        <div class="container">
          <div class="row">
            <div class="contact-caption clearfix">
              <div class="contact-heading text-center">
                <h2>Take Appointment</h2>
              </div>
              <div class="col-md-5 contact-info text-left">
                <h3>Take Appointment</h3>
                  {% block content %}

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_slots' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <!-- <a href="{% url 'person_changelist' %}">Nevermind</a> -->
  </form>


 <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_slot").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>


            </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

Hospital_management/catalog/templates/author.html
{% extends "base_lib.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Author Detials</h2>

  <p>The library has the following record counts:</p>
  <!--<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>-->
  <table>
      <th>
        <td>First Name</td>
        <td>Last Name</td>
        <td>DOB</td>
        <td>DOD</td>
      </th>
    {%for ans in ans_dict%}
      <tr>
        <td></td>
        <td>{{ans.first_name}}</td>>
        <td>  {{ ans.last_name}} </td>
        <td>  {{ ans.date_of_birth}} </td>
        <!--<td>  {{ bb.genre}} </td>-->
        <!--{%for gen in bb.genre.all %}
          <td>  {{ gen.name}} </td>
        {% endfor %}-->
      </tr>
      
    {% endfor %}
    </table>

{% endblock %}

Hospital_management/catalog/templates/base_new.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--===============================================================================================-->	
    <meta name="description" content="">
    <!--===============================================================================================-->	
    <meta name="author" content="">
    <!--===============================================================================================-->	
	<title>DOCTOR - Responsive HTML &amp; Bootstrap Template</title>
	<link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %} ">
	<!--===============================================================================================-->	
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
	<!--===============================================================================================-->	
	<link rel="stylesheet" href="{% static 'main/css/style.css' %} ">
	<!--===============================================================================================-->	
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css'>
	<!--===============================================================================================-->	
	<link href='http://fonts.googleapis.com/css?family=BenchNine:300,400,700' rel='stylesheet' type='text/css'>
	<!--===============================================================================================-->	
	<script src="{% static 'main/js/modernizr.js' %} "></script>
	<!--===============================================================================================-->	


</head>
<body>
	
	<!-- ====================================================
	header section -->
	<header class="top-header">
		<div class="container">
			<div class="row">
				<div class="col-xs-5 header-logo">
					<br>
					<a href="index.html"><img src="img/logo.png" alt="" class="img-responsive logo"></a>
				</div>

				<div class="col-md-7">
					<nav class="navbar navbar-default">
					  <div class="container-fluid nav-bar">
					    <!-- Brand and toggle get grouped for better mobile display -->
					    <div class="navbar-header">
					      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					        <span class="sr-only">Toggle navigation</span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					      </button>
					    </div>

					    <!-- Collect the nav links, forms, and other content for toggling -->
					    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					      
					      <ul class="nav navbar-nav navbar-right">
					        <li><a class="menu active" href="#home" >Home</a></li>
					        <li><a class="menu" href="#about">about us</a></li>
					        <li><a class="menu" href="#service">our services </a></li>
					        <li><a class="menu" href="#team">our team</a></li>
					        <li><a class="menu" href="#contact"> Contact </a></li>
					        <li><a class="menu" href="{% url 'login'%}"> Login </a></li>
					      </ul>
					    </div><!-- /navbar-collapse -->
					  </div><!-- / .container-fluid -->
					</nav>
				</div>
			</div>
		</div>
	</header> <!-- end of header area -->

Hospital_management/catalog/templates/book.html
{% extends "base_lib.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

Hospital_management/catalog/templates/register2.html
{% load static%}
<html lang="en">
<head>
	<title>Sign Up Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href=" {% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"  href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>

<body>
	
	
	
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" name="Registration_form" method="post">
					 {% csrf_token %}
					 {{ user_form.non_field_errors }}
					<span class="login100-form-title p-b-26">
						Sign Up 
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<datalist id="User_list">
						{% for users in user%}
							<option value="{{users.id}}">
						{% endfor %}
					</datalist>

					<div class="wrap-input100" >
						 <input  class="input100" type="Integer" list="User_list" id="id_u_id" name="u_id" for="{{ user_form.u_id.id_for_label }}">
						<span class="focus-input100" data-placeholder="u_id"></span> 
					</div>
					{{ user_form.u_id.errors }}


					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_First_Name" name="First_Name" for="{{ user_form.First_Name.id_for_label }}">
						<span class="focus-input100" data-placeholder="First_Name"></span> 
					</div>
					{{ user_form.First_Name.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_Last_Name" name="Last_Name" for="{{ user_form.Last_Name.id_for_label }}">
						<span class="focus-input100" data-placeholder="Last_Name"></span> 
					</div>
					{{ user_form.Last_Name.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_Middle_Name" name="Middle_Name" for="{{ user_form.Middle_Name.id_for_label }}">
						<span class="focus-input100" data-placeholder="Middle_Name"></span> 
					</div>
					{{ user_form.Middle_Name.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_Address" name="Address" for="{{ user_form.Address.id_for_label }}">
						<span class="focus-input100" data-placeholder="Address"></span> 
					</div>
					{{ user_form.Address.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="Date" id="id_Date_Of_Birth" name="Date_Of_Birth" for="{{ user_form.Date_Of_Birth.id_for_label }}">
						<span class="focus-input100" data-placeholder="Date_Of_Birth"></span> 
					</div>
					{{ user_form.Date_Of_Birth.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_Blood_Grp" name="Blood_Grp" for="{{ user_form.Blood_Grp.id_for_label }}">
						<span class="focus-input100" data-placeholder="Blood_Grp"></span> 
					</div>
					{{ user_form.Blood_Grp.errors }}


					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Register
							</button>
						</div>
					</div>

		</form>

		<script src=" {% static 'vendor/jquery/jquery-3.2.1.min.js' %}" ></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %} "></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>
		<!--<form method="post">
			{% csrf_token %}

			<!--{{user_form.as_p}}-->
		<!--</form>-->
	<!--<form method="post">
		 {% csrf_token %}
		{% for field in user_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        <b>{{ field.label.id}}</b>
    </div>
{% endfor %}
		<button type="submit"> submit</button>
	</form>-->

	<!--<b>{{ user_form.password1.id_for_label }}</b>
	<b>{{ user_form.password2.id_for_label }}</b>
	<b>{{ user_form.username.id_for_label }}</b>
	<b>{{ user_form.first_name.id_for_label }}</b>
	<b>{{ user_form.last_name.id_for_label }}</b>
	<b>{{ user_form.email.id_for_label }}</b>


	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="post">
					<span class="login100-form-title p-b-26">
						Sign Up
					</span>
					{% csrf_token %}
					{{ user_form.non_field_errors }}
					<div class="wrap-input100" >
				    	{{ form.username.errors }}
				    	<label for="{{ user_form.username.id_for_label }}">Username:</label>
				    	 <!--<input  class="input100" type="text" id="id_last_name" name="last_name" >
				    	 <span class="focus-input100" data-placeholder="Email Id" for="{{ user_form.username.id_for_label }}"></span>-->
				    	<!--{{ user_form.username }}
				    	</input>
				    </div>
				    <div class="wrap-input100" >
				    	{{ user_form.password1.errors }}
				    	<label for="{{ user_form.password1.id_for_label }}">Password1:</label>
				    	{{ user_form.password1 }}
					</div>
					<div class="wrap-input100" >
						    {{ user_form.password2.errors }}
						    <label for="{{ user_form.password2.id_for_label }}">Password2:</label>
						    {{ user_form.password2}}
					</div>
					<div class="wrap-input100" >
						    {{ user_form.first_name.errors }}
						    <label for="{{ user_form.first_name.id_for_label }}">FIRST name</label>
						    {{ user_form.first_name }}
					</div>
					<div class="wrap-input100" >
						    {{ user_form.last_name.errors }}
						    <label for="{{ user_form.last_name.id_for_label }}">Last name</label>
						    {{ user_form.last_name }}
					</div>
					<div class="wrap-input100" >
						    {{ user_form.email.errors }}
						    <label for="{{ user_form.email_name.id_for_label }}">email</label>
						    {{ user_form.email }}
					</div>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
								<button class="login100-form-btn" type="submit">
											Sign Up
								</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>